### ISSUE TITLE
add support for self-hosted instances

### ISSUE THREAD

**Issue by Midou36O** [rexovolt/termivolt#3]
Is termivolt capable of running in self hosted instances (aka not using revolt's official website), if no would you be able to implement it?

**Comment by Rexogamer** [comment]
Not at the moment, although I'd be more than happy to add this.

**Comment by Rexogamer** [comment]
Quick question - do you know of any self-hosted instances that could be used for testing?

**Comment by Midou36O** [comment]
i don't know any of them except mine that isn't ready yet and is currently broken.. i could try and fix it whenever i have time and give you the permission to test it, how does that sound?

**Comment by Rexogamer** [comment]
Sounds good to me - if you're experiencing any issues with your instance, I'd recommend taking a look at [the self-hosted repo's issues](https://github.com/revoltchat/self-hosted/issues) for advice :)

**Comment by Midou36O** [comment]
*since i got banned from discord* i have more motivation to self host revolt so this should come sooner than expected.

**Comment by Rexogamer** [comment]
This should now be supported in 0.3.x and 0.4.x 🎉
